title: Mohammad Ahmadi Sadr
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer<br>
  Contact:<br>
    <a href="tel:+14384540470"> +1 438 454 0470</a><br>
    <a href="mailto:mohamadahmadisadr@gmail.com"> mohamadahmadisadr@gmail.com</a>
    <a href="https://www.linkedin.com/in/mohamadahmadisadr/">Linkedin</a><br>
    <a href="https://www.github.com/mohamadahmadisadr/">github</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-XHJ4S9BBFE # your Google Analytics tracking ID here
